name: Publish
on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [14.16.1]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2.3.4

      - name: Install Node.js  ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Publish Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
