name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]
        node-version: [14.17.6]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2.7.0

      - name: Install Node.js  ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Publish Electron app
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npm run publish
