name: Build/Release

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2.7.0

      - name: Install Node.js  ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
  
  unit-tests:
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2.7.0

      - name: Install Node.js  ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:ci
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
            token: ${{ secrets.CODECOV_TOKEN }}

  e2e-tests:
    needs: unit-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2.7.0

      - name: Install Node.js  ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run E2E tests
        run: xvfb-run npm run test:e2e


  build:
    needs: e2e-tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-2019]
        node-version: [14.17.6]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2.7.0

      - name: Install Node.js  ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: npm run make

  release:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2.7.0

      - name: Install Node.js  ${{ matrix.node-version }}, NPM and Yarn
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: npm run semantic-release
